# Generated by Django 6.0.5 on 2026-05-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_fotografia_data_fotografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotografia',
            name='foto_nome',
        ),
        migrations.AddField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/%Y/%m/%d'),
        ),
    ]
